-- Create system_modules table (baseline for subsequent migrations)
CREATE TABLE IF NOT EXISTS public.system_modules (
  id UUID DEFAULT gen_random_uuid() NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  version TEXT DEFAULT '1.0.0'::text,
  is_active BOOLEAN DEFAULT true NOT NULL,
  default_limits JSONB DEFAULT '{}'::jsonb,
  dependencies TEXT[] DEFAULT '{}'::text[],
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  author TEXT,
  license TEXT DEFAULT 'MIT'::text,
  homepage TEXT,
  repository TEXT,
  peer_dependencies JSONB DEFAULT '[]'::jsonb,
  min_core_version TEXT DEFAULT '1.0.0'::text,
  max_core_version TEXT,
  entry_point TEXT DEFAULT 'index.tsx'::text,
  routes JSONB DEFAULT '[]'::jsonb,
  components JSONB DEFAULT '[]'::jsonb,
  services JSONB DEFAULT '[]'::jsonb,
  hooks JSONB DEFAULT '[]'::jsonb,
  required_permissions JSONB DEFAULT '["read"]'::jsonb,
  subscription_tiers JSONB DEFAULT '["basic", "pro", "enterprise"]'::jsonb,
  resource_limits JSONB DEFAULT '{}'::jsonb,
  load_order INTEGER DEFAULT 100,
  auto_load BOOLEAN DEFAULT false,
  can_unload BOOLEAN DEFAULT true,
  development_mode BOOLEAN DEFAULT false,
  hot_reload BOOLEAN DEFAULT true,
  sandboxed BOOLEAN DEFAULT false,
  maturity_status TEXT DEFAULT 'planning'::text NOT NULL,
  development_stage JSONB DEFAULT '{"stage": "planning", "progress": 0, "milestones": [], "requirements": []}'::jsonb,
  promoted_to_production_at TIMESTAMPTZ,
  promoted_by UUID,
  type TEXT DEFAULT 'business'::text NOT NULL,
  ai_capabilities TEXT[] DEFAULT '{}'::text[],
  ai_level TEXT DEFAULT 'none'::text,
  ai_description TEXT,
  ai_features JSONB DEFAULT '{}'::jsonb,
  CONSTRAINT system_modules_ai_level_check CHECK (ai_level = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text, 'none'::text])),
  CONSTRAINT system_modules_maturity_status_check CHECK (maturity_status = ANY (ARRAY['planning'::text, 'alpha'::text, 'beta'::text, 'production'::text])),
  CONSTRAINT system_modules_type_check CHECK (type = ANY (ARRAY['super_admin'::text, 'foundation'::text, 'business'::text])),
  UNIQUE(name)
);

